service: zoopla-sale-advert-capture
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamRoleStatements:
    - Action:
        - s3:PutObject
      Effect: Allow
      Resource:
        Fn::Join:
          - '/'
          - - !GetAtt ZooplaSaleAdvertsBucket.Arn
            - '*'

functions:
  capture:
    handler: capture.handler
    description: |
      Given a Zoopla sale advert URL: takes a snapshot of the page, then saves it to storage.
    environment:
      BUCKET: !Ref ZooplaSaleAdvertsBucket
    events:
      - eventBridge:
          pattern:
            source:
              - property-data.zoopla-sale-advert-schedule
            detail-type:
              - SNAPSHOT_REQUESTED

resources:
  Outputs:
    ZooplaSaleAdvertsBucketName:
      Value: !Ref ZooplaSaleAdvertsBucket
      Export:
        Name: ZooplaSaleAdvertsBucketName
  Resources:
    ZooplaSaleAdvertsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        VersioningConfiguration:
          Status: Enabled
