service: zoopla-sale-advert-capture
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
  iamRoleStatements:
    - Action:
        - s3:PutObject
      Effect: Allow
      Resource:
        Fn::Join:
          - '/'
          - - !GetAtt ZooplaSaleAdvertsBucket.Arn
            - '*'

functions:
  capture:
    handler: capture.handler
    description: |
      Given a SNAPSHOT_REQUESTED event: takes a snapshot of the page, then saves it to storage.
    environment:
      BUCKET: !Ref ZooplaSaleAdvertsBucket
    events:
      - eventBridge:
          pattern:
            source:
              - property-data.zoopla-sale-advert-schedule
            detail-type:
              - SNAPSHOT_REQUESTED
    layers:
      - arn:aws:lambda:${self:provider.region}:580247275435:layer:LambdaInsightsExtension:12
    memorySize: 256
#    reservedConcurrency: 0      # Throttle for emergencies.

resources:
  Outputs:
    ZooplaSaleAdvertsBucketName:
      Value: !Ref ZooplaSaleAdvertsBucket
      Export:
        Name: ZooplaSaleAdvertsBucketName
  Resources:
    ZooplaSaleAdvertsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        VersioningConfiguration:
          Status: Enabled
