service: zoopla-sale-advert-capture
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
  iamRoleStatements:
    - Action: dynamodb:PutItem
      Effect: Allow
      Resource: !GetAtt ZooplaSaleAdvertsIndexTable.Arn
  logRetentionInDays: 14

functions:
  capture:
    handler: capture.handler
    description: |
      Given a SNAPSHOT_REQUESTED event: takes a snapshot of the page, then indexes it.
    environment:
      INDEX_TABLE: !Ref ZooplaSaleAdvertsIndexTable
    events:
      - eventBridge:
          pattern:
            source:
              - prefix: property-data.
            detail-type:
              - SNAPSHOT_REQUESTED
    layers:
      - arn:aws:lambda:${self:provider.region}:580247275435:layer:LambdaInsightsExtension:12
    memorySize: 256
    reservedConcurrency: 1      # Set to zero to throttle for emergencies.

resources:
  Outputs:
    ZooplaSaleAdvertsIndexTableStreamArn:
      Value: !GetAtt ZooplaSaleAdvertsIndexTable.StreamArn
      Export:
        Name: ZooplaSaleAdvertsIndexTableStreamArn
  Resources:
    ZooplaSaleAdvertsIndexTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
