service: zoopla-sale-advert-capture
frameworkVersion: '2'

provider:
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamRoleStatements:
    - Action: dynamodb:PutItem
      Effect: Allow
      Resource: !GetAtt ZooplaSaleAdvertsIndexTable.Arn
    - Action: events:PutEvents
      Effect: Allow
      Resource: arn:aws:events:*:*:event-bus/*
    - Action: sqs:SendMessage
      Effect: Allow
      Resource: !GetAtt ZooplaSaleAdvertsCaptureDLQ.Arn
  logRetentionInDays: 14

functions:
  capture:
    handler: capture.handler
    description: |
      Given a SNAPSHOT_REQUESTED event: takes a snapshot of the page, then indexes it. Expired adverts emit a ZOOPLA_SALE_ADVERT_EXPIRED event.
    environment:
      EVENT_BUS: default
      EVENT_SOURCE: property-data.${self:service}
      INDEX_TABLE: !Ref ZooplaSaleAdvertsIndexTable
    events:
      - eventBridge:
          pattern:
            source:
              - prefix: property-data.
            detail-type:
              - SNAPSHOT_REQUESTED
    memorySize: 256
    reservedConcurrency: 1      # Set to zero to throttle for emergencies.

resources:
  Outputs:
    ZooplaSaleAdvertsIndexTableStreamArn:
      Value: !GetAtt ZooplaSaleAdvertsIndexTable.StreamArn
      Export:
        Name: ZooplaSaleAdvertsIndexTableStreamArn
  Resources:
    CaptureLambdaEvConf:
      Type: AWS::Lambda::EventInvokeConfig
      Properties:
        DestinationConfig:
          OnFailure:
            Destination: !GetAtt ZooplaSaleAdvertsCaptureDLQ.Arn
        FunctionName: !Ref CaptureLambdaFunction
        Qualifier: $LATEST
    ZooplaSaleAdvertsCaptureDLQ:
      Type: AWS::SQS::Queue
      Properties:
        ReceiveMessageWaitTimeSeconds: 20
        Tags:
          - Key: DLQ
            Value: true
    ZooplaSaleAdvertsIndexTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
