---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  GitHubOIDCThumbprint:
    Type: String
    MaxLength: 40
    MinLength: 40
  GitHubRepoOwner:
    Type: String
  GitHubRepoName:
    Type: String

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - !Ref GitHubOIDCThumbprint
      Url: https://token.actions.githubusercontent.com

  ServerlessFrameworkRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRoleWithWebIdentity
            Effect: Allow
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:sub": !Sub "repo:${GitHubRepoOwner}/${GitHubRepoName}:ref:refs/heads/main"
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
            Principal:
              Federated: !Ref GitHubOIDCProvider
      Path: !Sub "/${GitHubRepoOwner}/"
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: cloudformation:*
                Effect: Allow
                Resource: "*"
              - Action: s3:ListBucket
                Effect: Allow
                Resource: "arn:aws:s3:::*-serverlessdeploy*-*"
              - Action: s3:*
                Effect: Allow
                Resource: "arn:aws:s3:::*-serverlessdeploy*-*/serverless/*/dev/*/*"
          PolicyName: CloudFormationInvocation
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - dynamodb:*
                  - iam:GetRole
                  - lambda:*
                  - sqs:*
                Effect: Allow
                Condition:
                  StringEquals:
                    "aws:CalledViaLast": "cloudformation.amazonaws.com"
                Resource: "*"
          PolicyName: CloudFormationExecution
      RoleName: !Ref GitHubRepoName
