service: zoopla-sale-advert-archive
frameworkVersion: '2'

provider:
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  iamRoleStatements:
    - Action: s3:PutObject
      Effect: Allow
      Resource:
        Fn::Join:
          - '/'
          - - !GetAtt ZooplaSaleAdvertsArchiveBucket.Arn
            - '*'
  logRetentionInDays: 14

functions:
  archive:
    handler: archive.handler
    description: |
      Given a Zoopla sale advert snapshot: de-duplicate consecutive snapshots and archive new content only.
    environment:
      ARCHIVE_BUCKET: !Ref ZooplaSaleAdvertsArchiveBucket
    events:
      - stream:
          type: dynamodb
          arn: !ImportValue ZooplaSaleAdvertsIndexTableStreamArn
    memorySize: 256
    reservedConcurrency: 1

resources:
  Resources:
    ZooplaSaleAdvertsArchiveBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        VersioningConfiguration:
          Status: Enabled
