service: advert-urls
frameworkVersion: '2'

provider:
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamRoleStatements:
    - Action:
        - events:PutEvents
      Effect: Allow
      Resource: 'arn:aws:events:*:*:event-bus/*'
  logRetentionInDays: 14

functions:
  decode:
    handler: handler.decode
    description: |
      Given an advert URL: decodes the advert type and platform, then emits a corresponding *_ADVERT_IDENTIFIED event.
    environment:
      EVENT_BUS: default
      EVENT_SOURCE: property-data.${self:service}
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt Urls.StreamArn
    memorySize: 256
    reservedConcurrency: 1

resources:
  Resources:
    Urls:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: KEYS_ONLY
