service: advert-urls
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    lambda: true
  iamRoleStatements:
    - Action:
        - SNS:Publish
      Effect: Allow
      Resource: !Ref ZooplaSaleAdvertDecodedTopic

functions:
  decode:
    handler: handler.decode
    environment:
      ZOOPLA_SALE_TOPIC_ARN: !Ref ZooplaSaleAdvertDecodedTopic
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt UrlsTable.StreamArn

resources:
  Resources:
    UrlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        StreamSpecification:
          StreamViewType: KEYS_ONLY
        TableName: urls
    ZooplaSaleAdvertDecodedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ZooplaSaleAdvertDecodedTopic
