service: zoopla-sale-advert-extract
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
  iamRoleStatements:
    - Action:
        - dynamodb:PutItem
      Effect: Allow
      Resource: !GetAtt ZooplaSaleAdvertsDataLakeTable.Arn

functions:
  extract:
    handler: extract.handler
    description: |
      Given a Zoopla sale advert page snapshot: parse snapshot data and persist into a data lake.
    environment:
      DATA_LAKE_TABLE: !Ref ZooplaSaleAdvertsDataLakeTable
    events:
      - stream:
          type: dynamodb
          arn: !ImportValue ZooplaSaleAdvertsIndexTableStreamArn
    layers:
      - arn:aws:lambda:${self:provider.region}:580247275435:layer:LambdaInsightsExtension:12
    memorySize: 256

resources:
  Resources:
    ZooplaSaleAdvertsDataLakeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: time
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
