service: zoopla-sale-advert-extract
frameworkVersion: '2'

provider:
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamRoleStatements:
    - Action:
        - dynamodb:PutItem
      Effect: Allow
      Resource: !GetAtt ZooplaSaleAdvertsDataLakeTable.Arn
  logRetentionInDays: 14

functions:
  extract:
    handler: extract.handler
    description: |
      Given a Zoopla sale advert page snapshot: parse snapshot data and persist into a data lake.
    environment:
      DATA_LAKE_TABLE: !Ref ZooplaSaleAdvertsDataLakeTable
    events:
      - stream:
          type: dynamodb
          arn: !ImportValue ZooplaSaleAdvertsIndexTableStreamArn
    memorySize: 256
    reservedConcurrency: 1

resources:
  Resources:
    ZooplaSaleAdvertsDataLakeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: time
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
