service: zoopla-sale-advert-schedule
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  tags:
    SERVICE: ${self:service}
  tracing:
    lambda: true
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
  iamRoleStatements:
    - Action: dynamodb:PutItem
      Effect: Allow
      Resource: !GetAtt ZooplaSaleAdvertsSchedule.Arn
    - Action: events:PutEvents
      Effect: Allow
      Resource: 'arn:aws:events:*:*:event-bus/*'
  logRetentionInDays: 14

functions:
  new:
    handler: handler.newHandler
    description: |
      Given a ZOOPLA_SALE_ADVERT_IDENTIFIED event: emits a SNAPSHOT_REQUESTED event, and schedules the next snapshot.
    environment:
      EVENT_BUS: default
      EVENT_SOURCE: property-data.${self:service}
      EVENT_TYPE: SNAPSHOT_REQUESTED
      TTL: 21600
      SCHEDULE: !Ref ZooplaSaleAdvertsSchedule
    events:
      - eventBridge:
          pattern:
            source:
              - property-data.advert-urls
            detail-type:
              - ZOOPLA_SALE_ADVERT_IDENTIFIED
    layers:
      - arn:aws:lambda:${self:provider.region}:580247275435:layer:LambdaInsightsExtension:12
    memorySize: 256
    reservedConcurrency: 1
  repeat:
    handler: handler.repeatHandler
    description: |
      Given an expired Zoopla sale advert snapshot: emits a SNAPSHOT_REQUESTED event, and reschedules another snapshot.
    environment:
      EVENT_BUS: default
      EVENT_SOURCE: property-data.${self:service}
      EVENT_TYPE: SNAPSHOT_REQUESTED
      TTL: 21600
      SCHEDULE: !Ref ZooplaSaleAdvertsSchedule
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt ZooplaSaleAdvertsSchedule.StreamArn
    layers:
      - arn:aws:lambda:${self:provider.region}:580247275435:layer:LambdaInsightsExtension:12
    memorySize: 256
    reservedConcurrency: 1

resources:
  Resources:
    ZooplaSaleAdvertsSchedule:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: OLD_IMAGE
        TableName: ${self:service}
        TimeToLiveSpecification:
          AttributeName: expiry
          Enabled: true
